version: "3.8"
services: 
  backend: 
    build: 
      context: ./backend
    volumes:
      - ./backend/:/backend
    ports: 
      - '8000:8000'
    container_name: backend
    # depends_on:
    #   - db
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgres/data
  #   environment:
  #     - POSTGRES_DB=PostgreSQL
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '5432:5432'

